{
 "title": "Dashboard-demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "steering_angle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "steering_angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "throttle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "acceleration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "acc_x" ], "type": "field" }
      ],
      [
       { "params": [ "acc_y" ], "type": "field" }
      ],
      [
       { "params": [ "acc_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "throttle histogramm",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "steering_angle histogramm",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "steering_angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "angular acceleration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "ang_acc_x" ], "type": "field" }
      ],
      [
       { "params": [ "ang_acc_y" ], "type": "field" }
      ],
      [
       { "params": [ "ang_acc_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "records",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "istep" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "wheel encoders",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "SELECT \"wheelEncoderLF\", \"wheelEncoderLR\", \"wheelEncoderRF\", \"wheelEncoderRR\" FROM \"DonkeySimulator\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "wheelEncoderLF" ], "type": "field" }
      ],
      [
       { "params": [ "wheelEncoderLR" ], "type": "field" }
      ],
      [
       { "params": [ "wheelEncoderRF" ], "type": "field" }
      ],
      [
       { "params": [ "wheelEncoderRR" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "cte",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "SELECT \"value\" FROM \"donkey\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "cte" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "position",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "SELECT \"steering_angle\" FROM \"DonkeySimulator\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pos_x" ], "type": "field" }
      ],
      [
       { "params": [ "pos_y" ], "type": "field" }
      ],
      [
       { "params": [ "pos_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "race track",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "pos_x" ], "type": "field" }
      ],
      [
       { "params": [ "pos_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}