{
 "title": "DIYrobocars-RacingDashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<h1> DIYrobocars Virtual Racing League</h1>\n<h4> Parking Lot Nerds: Ann Arbor, Detroit, Ottawa, Stuttgart </h4>\n<small><small><small><small><small><small>   Rainer Bareiß, May 3rd, 2020 powered by InfluxDB, Grafana </small></small></small></small></small></small>"
  },
  {
   "title": "steering_angle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "steering_angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "throttle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 3 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 3 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "select * from demo",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "records",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "istep" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "steering_angle histogramm",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "steering_angle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "track",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 15, "w": 10, "x": 5, "y": 8 },
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "pos_x" ], "type": "field" }
      ],
      [
       { "params": [ "pos_z" ], "type": "field" }
      ],
      [
       { "params": [ "speed" ], "type": "field" }
      ],
      [
       { "params": [ "throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "acceleration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "acc_x" ], "type": "field" }
      ],
      [
       { "params": [ "acc_y" ], "type": "field" }
      ],
      [
       { "params": [ "acc_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "throttle histogramm",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "throttle" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "angular acceleration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "select": [
      [
       { "params": [ "ang_acc_x" ], "type": "field" }
      ],
      [
       { "params": [ "ang_acc_y" ], "type": "field" }
      ],
      [
       { "params": [ "ang_acc_z" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "cte",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "SELECT \"value\" FROM \"donkey\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "cte" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "wheel encoders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "DonkeySimulator",
     "query": "SELECT \"wheelEncoderLF\", \"wheelEncoderLR\", \"wheelEncoderRF\", \"wheelEncoderRR\" FROM \"DonkeySimulator\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "wheelEncoderLF" ], "type": "field" }
      ],
      [
       { "params": [ "wheelEncoderLR" ], "type": "field" }
      ],
      [
       { "params": [ "wheelEncoderRF" ], "type": "field" }
      ],
      [
       { "params": [ "wheelEncoderRR" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}